# This workflow will deploy the artifacts from the master build to firebase pong site perscribed in firebase.json
# For more information see: https://github.com/w9jds/firebase-action

jobs:
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:pong
        env:
          FIREBASE_TOKEN: 1//0dIC241leb9v9CgYIARAAGA0SNwF-L9Irq4HqDGlmNXQMqr2Fav7s4zkwAH4_WsQOrM_z7rCQtBHoXl-gjeWD6_TONEo583ZQp4E
